# This is a basic workflow to help you get started with Actions

name: Test and build

# Controls when the workflow will run
on: 
  push: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    name: Test and build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'
          cache: 'yarn'
          
      - name: Run jest tests
        run: yarn test
        
      - name: Build dist
        run: yarn build
